### ISSUE TITLE
FSharp.Data.Xsd

### ISSUE THREAD

**Issue by giacomociti** [fsprojects/FsProjectsAdmin#13]
hello, can I transfer [FSharp.Data.Xsd](https://github.com/giacomociti/FSharp.Data.Xsd)?

**Comment by sergey-tihon** [comment]
I've sent you an invitation to `fsprojects-transfer` org, plz accept it and transfer repo there, then I will complete the transfer to `fsprojects`.

**Comment by sergey-tihon** [comment]
Sorry @giacomociti, I missed somehow the moment when you moved the repository.
The transition to fsprojects is done, so please follow the steps from [onboarding process](https://github.com/fsprojects/FsProjectsAdmin#onboarding-process): update readme, link to the site, nuget package owners and etc.

Thank you @giacomociti !

**Comment by giacomociti** [comment]
Thanks, I'll do the onboarding  steps in a couple of weeks since right now I'm on holidays without my laptop.

**Comment by sergey-tihon** [comment]
Have a nice holidays!

**Comment by giacomociti** [comment]
Hi @sergey-tihon , I think I did my onboarding duty, although:
fsprojects is still _pending approval_ on NuGet
I can't fix the link in the repo description (no _Edit_ button in sight, I hope_ you can do it)
The Travis build is failing and I'm afraid it has to do with a recent update to Mono 5.0

**Comment by sergey-tihon** [comment]
> fsprojects is still pending approval on NuGet

As I know, @dsyme is the only owner of this account now.
So we need to ask him gently here to approve all pending requests.

> I can't fix the link in the repo description (no Edit button in sight, I hope_ you can do it)

I did it and hopefully fixed your permissions as well

> The Travis build is failing and I'm afraid it has to do with a recent update to Mono 5.0

Yes, looks like a known issues, you uses old version on FAKE that does not play nicely on Mono 5.0, could you please update it to the latest version of FAKE?

**Comment by dsyme** [comment]
M y apologies, have been on vacation

@giacomociti fsprojects is now an approved owner on nuget. 

Anything else you need? 

thx

**Comment by giacomociti** [comment]
Thanks a lot @sergey-tihon and @dsyme .
I think the only issue left is the Travis build although it is not related to the migration to fsprojects (but of course any help is highly appreciated).
I would appreciate also any kind of advice on the roadmap for this project: is it worth to start diverging from the code cloned from F# Data? You know this is just a thin wrapper around the XML type provider of F# Data (it's been also submitted as a PR but I'm afraid it won't be merged). Modifying some of the underlying code may help to implement a few minor improvements, especially related to simple data types.
Personally I'm not sure this is worth the trouble.
