### ISSUE TITLE
Transfer TickSpec

### ISSUE THREAD

**Issue by ptrelford** [fsprojects/FsProjectsAdmin#14]
TickSpec is a mature open source testing library for .Net written in F#.
The original repository was held on CodePlex which is closing down soon.
Some users of the library have created their own clones of the repository on GitHub, others are unsure which repository to use, see thread:

-  https://twitter.com/ChaloupkaMilos/status/903169577210830848

I propose that the following repository is transferred to fsprojects as a common repository:

- https://github.com/bartelink/tickspec

That way users can merge changes to a common repository.

**Comment by sergey-tihon** [comment]
@bartelink I've sent you an invitation to https://github.com/fsprojects-transfer/, please join and do 1st transfer

**Comment by bartelink** [comment]
@sergey-tihon It's underway...

**Comment by bartelink** [comment]
@sergey-tihon seems to be transferred... the readme was coped from codeplex some time ago with all links as they were, i.e. there may well be broken links

**Comment by sergey-tihon** [comment]
Transfer is complete, here is the repo https://github.com/fsprojects/tickspec
@bartelink and @ptrelford are admins 

May I ask you to check steps from migration guide https://github.com/fsprojects/FsProjectsAdmin, update README and share NuGet package with https://www.nuget.org/profiles/fsprojects ?

Thank you

**Comment by bartelink** [comment]
@sergey-tihon all NuGet / AppVeyor / Travis config / permissions were configured and/or belong to @ptrelford - I only ingested the repo and pushed some commits (inc a readme.md which I produced by pasting the source from codeplex about 1 year ago). Will be AFK for some time but will check back in later.

**Comment by ptrelford** [comment]
@bartelink @sergey-tihon please ping me your Nuget user names and I'll add you as owners

**Comment by bartelink** [comment]
@ptrelford my NuGet username is `bartelink`
