### ISSUE TITLE
Maintaining GraphProvider

### ISSUE THREAD

**Issue by vukovinski** [fsprojects/FsProjectsAdmin#15]
Hello, I'd like to be added as the maintainer of GraphProvider. I use DGML routinely for domain modeling.

**Comment by sergey-tihon** [comment]
Cool, thank you for for your willingness. 
I think that it should be possible, we just need as ask @forki and @mexx.

@vukovinski could you please describe in couple sentences what you want to change/add to the project? Thank you

**Comment by mexx** [comment]
I have no objections, go for it.

**Comment by sergey-tihon** [comment]
@forki ?

**Comment by forki** [comment]
Fine with me

Am 24.09.2017 17:25 schrieb "Sergey Tihon" <notifications@github.com>:

**Comment by dsyme** [comment]
@vukovinski THis is a lnog time ago, but better late than never, I sent an invitation. You probably forked it?
