### ISSUE TITLE
Request for transferring FsRandom to fsprojects

### ISSUE THREAD

**Issue by kos59125** [fsprojects/FsProjectsAdmin#17]
[FsRandom](https://github.com/kos59125/FsRandom) is an fsharp library to generate random numbers in the way of functional programming including computation expressions.
It is extensible to support adding pseudo-random number generators and random functions such like generating random passwords or random user names.
Also, it can leverage System.Random class and its subclasses defined in libraries like MathNet.Numerics.

**Comment by kos59125** [comment]
@sergey-tihon Thanks. I have just transferred my repo to `fsprojects-transfer`.

**Comment by sergey-tihon** [comment]
I've finished the transfer. 
Please update the `README.md`, add maintainers, share `NuGet` package with fsprojects account and continue on the list - https://github.com/fsprojects/FsProjectsAdmin#requesting-transfer
