### ISSUE TITLE
Want to transfer FSharp.Span.Utils

### ISSUE THREAD

**Issue by cannorin** [fsprojects/FsProjectsAdmin#19]
Hello,

Unfortunately, [I have already polluted the NuGet namespace with `FSharp.Foo` packages](https://www.nuget.org/packages?q=cannorin) before I found and read [the guideline](http://fsharp.github.io/2014/09/19/fsharp-libraries.html).

Since few people expect for me use those libraries, I'm considering either

1. transfer the ownership to fsprojects and become a maintainer, taking responsibility.
2. or rename them completely.

In particular, [`FSharp.Span.Utils`](https://github.com/cannorin/FSharp.Span.Utils) seems falling into option 1; it's very small so that I can easily add docs and maintain, and thankfully [some people liked it](https://github.com/cannorin/FSharp.Span.Utils/stargazers) (not sure if it is actually used, though).

Can I transfer it to fsprojects?

**Comment by dsyme** [comment]
@cannorin Apologies we missed it. Did you transfer in?  You should be able to do it directly?

**Comment by cannorin** [comment]
@dsyme thanks! I was't a member of fsprojects at the moment I created this issue.

I've just transferred it to fsproject: https://github.com/fsprojects/FSharp.Span.Utils
but it seems I lost the admin access to it (maybe because of my oversight). could you or someone with an admin permission grant me the admin/maintainer access to the repo?

**Comment by sergey-tihon** [comment]
@cannorin please check again, I've changed your role from `Write` to `Admin`
and Welcome to fsprojects! 🥳
