### ISSUE TITLE
Additional members to syntactic versioning

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FsProjectsAdmin#20]
https://github.com/fsprojects/SyntacticVersioning/issues/34

**Comment by sergey-tihon** [comment]
<img width="641" alt="SyntacticVersioning-admins_·_F__Community_Project_Incubation_Space_Team" src="https://user-images.githubusercontent.com/1197905/68415256-fc73d200-01a2-11ea-904a-5a940a7f1053.png">
Done

**Comment by wallymathieu** [comment]
Sweet, thanks!
