### ISSUE TITLE
Setup group for f# codecs redis project

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FsProjectsAdmin#21]
https://github.com/fsprojects/FSharp.Codecs.Redis/issues/5

**Comment by sergey-tihon** [comment]
Also done
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/1197905/68415775-28438780-01a4-11ea-8860-2aecc88c4d5b.png">

**Comment by wallymathieu** [comment]
Sweet! Thanks!
