### ISSUE TITLE
Add @adz and @wallymathieu to fsharpplus-admin

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FsProjectsAdmin#22]
https://github.com/orgs/fsprojects/teams/fsharplus-admin
Add the users @adz and @wallymathieu

**Comment by sergey-tihon** [comment]
@cannorin @forki @gusty any objections?

**Comment by forki** [comment]
I'm fine with that

Sergey Tihon <notifications@github.com> schrieb am Sa., 18. Jan. 2020,
08:55:

**Comment by sergey-tihon** [comment]
I've added @wallymathieu and send intimation to @adz
