### ISSUE TITLE
Add @alfonsogarciacaro to F#+ Admins

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FsProjectsAdmin#24]
The more the merrier! Would be sweet to have help when it comes to Fable related workflows, see https://github.com/fsprojects/FSharpPlus/pull/392 for instance.

What do you think @cannorin @forki @gusty @adz ?

**Comment by gusty** [comment]
I think we all can benefit from having @alfonsogarciacaro as admin, specially now that we're trying to make F#+ and Fable 3 a real thing.

**Comment by cannorin** [comment]
:+1:

**Comment by alfonsogarciacaro** [comment]
Hi there! I'd be honored to join the team 😊 Just it may be difficult for me to watch everything happening in the repository so please be sure to ping me when you need my help 👍

**Comment by adz** [comment]
:+1:

**Comment by gusty** [comment]
Ok, no objections so far.

@forki could you add him?

Thanks

**Comment by forki** [comment]
Invitation sent

Gustavo Leon <notifications@github.com> schrieb am Di., 10. Nov. 2020,
17:16:

**Comment by gusty** [comment]
@forki it looks like @alfonsogarciacaro is now admin of FsProjects which if you both agree I welcome that, but he's still not member of F#+ admins.

Maybe he doesn't need to in that case?

**Comment by forki** [comment]
Now he can himself to that ;-)

Gustavo Leon <notifications@github.com> schrieb am Sa., 14. Nov. 2020,
11:00:

**Comment by alfonsogarciacaro** [comment]
Ah, sorry, I was confused by the workflow 😅 Ok, I've appointed myself as F#+ admin now and I've also gave me a salary rise. It should be ok to remove me as fsprojects admin now :)

**Comment by wallymathieu** [comment]
Perhaps @forki wants additional people to help him manage the administration of projects here on fsprojects
