### ISSUE TITLE
Interstellar

### ISSUE THREAD

**Issue by jwosty** [fsprojects/FsProjectsAdmin#25]
I'd love to have [Interstellar](https://github.com/jwosty/Interstellar) moved over here to fsprojects!

Related: fsharp/fsfoundation#854

**Comment by sergey-tihon** [comment]
Hi @jwosty 
I've send you invitation to https://github.com/fsprojects-transfer org, please move project there, then I will move it to fsprojects and return you back admin right

**Comment by jwosty** [comment]
@sergey-tihon transferred

**Comment by sergey-tihon** [comment]
Done, please check your permissions, [update readme](https://github.com/fsprojects/FsProjectsAdmin) and https://www.nuget.org/profiles/fsprojects as an owner for Interstellar NuGet packages

**Comment by jwosty** [comment]
Awesome, I've done both of those things. Although I can't see any settings tab or edit the repo description anymore.

**Comment by sergey-tihon** [comment]
Please try again - you have admin right on this repo

**Comment by jwosty** [comment]
It works now; thank you very much!
