### ISSUE TITLE
Move fsprojects/Fabulous to fsharp-mobile org

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/FsProjectsAdmin#45]
Recently, I created the organisation [fsharp-mobile](https://github.com/orgs/fsharp-mobile). It aims to regroup all the efforts around improving toolings and frameworks for desktop and mobile development with F#.

I am already hosting most of the work I did over the years such as the F# mobile templates, 3rd party support and additional variants for Fabulous. 

I would also like the main Fabulous repository to join this organisation if that's okay.

**Comment by TimLariviere** [comment]
Tagging for visibility just in case @sergey-tihon @dsyme

**Comment by sergey-tihon** [comment]
I do not mind personally. (Awesome work with Fabulous btw)

Just would be nice to have more than one admin for fsharp-mobile organization and more than one owner for packager published from new repos (in order to guarantee continuity)

**Comment by TimLariviere** [comment]
@edgarfgp is joining me as admin of the org.
I will create a shared owner account on NuGet as well.

Edit: Created an org account on NuGet https://www.nuget.org/profiles/fsharp-mobile

**Comment by dsyme** [comment]
Interesting and good move!

**Comment by dsyme** [comment]
You could maybe adopt a set of policies for the org, eg similar to the ones we use here?

Might be good to add one extra backup owner not actively involved in development just in case things chshte in 5 years or so - myself, or Sergey, or Tomas Petricek or similar - someone who can ask around for continuity maintainers if needed.

Please check fsharp.org for links that need adjusting

**Comment by TimLariviere** [comment]
Adopting the same policies (except for the incubation part) is a good idea. I did not think this far yet, but requiring 2 admins, docs, tests, licensing and FSSF CoC are great to have.

@dsyme would you be interested to join as a backup admin, since you originally created Fabulous?

For fsharp.org, I'll submit a PR once Fabulous is moved to the new org.

**Comment by dsyme** [comment]
@TimLariviere I'm happy to be backup backup yes :)

**Comment by dsyme** [comment]
@TimLariviere Can you do the move or do you need our help for that?

**Comment by TimLariviere** [comment]
@dsyme I have sent an invite to you.

>Can you do the move or do you need our help for that?

I would need your help. I don't have the rights to do the transfer.

**Comment by dsyme** [comment]
@TimLariviere I've transferred ownership!

**Comment by dsyme** [comment]
@TimLariviere On naming - I wonder if "fsharp-apps" or "fsapps" or "fsharp-appdev" or similar would be a better name for the org.

(Somehow "fsapps" would match "fslab" and "fsprojects" though there's no particular need to align along that dimension).

I do think "fabulous" is a really good name so in theory you could also call the whole org "fabulous-apps" or something but I know there's more under the org than just the things we originally called "fabulous" so it would take some shifting of words.

**Comment by sergey-tihon** [comment]
👍 for "fabulous-apps" or just "fabulous".

We already have `fsharp/fsharp` so why not `fabulous/fabulous`...

**Comment by TimLariviere** [comment]
@dsyme Awesome! Thanks a lot.

I would love to call the org `fabulous` but unfortunately that name is already taken.
Initially I called the org `fabulousfx` but someone pointed out it was confusing because we have a couple templates and packages that are not tied to Fabulous.

I'm discussing with @edgarfgp about this.

For now, I feel like `fsharp-mobile` conveys the idea behind the org better.

**Comment by dsyme** [comment]
The problem with "fsharp-mobile" is it's both too much and too little - there will be other approaches to mobile (fable-based especially), and the headline of the org is "mobile and desktop"

I think you could simply change the meaning of "fabulous" to be broader and incorporate what you want.

**Comment by TimLariviere** [comment]
That's a good point.
We settled on the name [fabulous-dev](https://github.com/fabulous-dev), which matches the website https://fabulous.dev

**Comment by TimLariviere** [comment]
Closing the issue since the transfer has been done. Thanks a lot :)
