### ISSUE TITLE
Move BioProviders to fsprojects

### ISSUE THREAD

**Issue by AlexKenna** [fsprojects/FsProjectsAdmin#46]
Could we please move [BioProviders](https://github.com/AlexKenna/BioProviders) to fsprojects? Recommended [here](https://github.com/AlexKenna/BioProviders/issues/2). Thank you!

**Comment by sergey-tihon** [comment]
@AlexKenna sure. just send you invitation to fsprojects org.

When you accept it, you will be able to transfer repo.

**Comment by AlexKenna** [comment]
Thanks @sergey-tihon. I have transferred the repository [here](https://github.com/fsprojects/BioProviders).

**Comment by sergey-tihon** [comment]
> After transfer you will be assigned GitHub “admin” rights on the project and are expected to continue to respond to issues and make new releases.

I've restored your Admin access to the repo.

> Packages - You may also receive a request to make the [fsprojects](https://www.nuget.org/profiles/fsprojects) nuget account a co-owner on any nuget packages associated with the repo. This is primarily to ensure the project can has the possibility of living on should you abandon it or not longer be able to publish nuget packages.

Can you please add [fsprojects](https://www.nuget.org/profiles/fsprojects) account to NuGet package owners?

> ❤️ Two maintainers - Your project should ideally have two people with “maintainer” or “admin” status (besides the backup admins).

Do you have an idea who may be 2nd maintainer on this repo?
