### ISSUE TITLE
dungpa / fsharp-cheatsheet Migration

### ISSUE THREAD

**Issue by SpiralOSS** [fsprojects/FsProjectsAdmin#47]
I started learning F# and this cheat-sheet was recommended to me and comes in and the top of searches (so it has some history) but I've found it largely out of date.

https://github.com/dungpa/fsharp-cheatsheet/pull/13#issuecomment-1758034463

I would be interested in updating it over time and @bartelink has offered to be a quiet second.

**Comment by bartelink** [comment]
@sergey-tihon Apologies if you're the wrong person to go atting on this, but would you be able to initiate/execute a transfer?

**Comment by dsyme** [comment]
@bartelink I think you need to fork this, or make a new clone, and move that over - @dungpa would need to transfer here

In this case we would accept a fork/clone, see policy under "Forking" https://github.com/fsprojects - note the conditions about adding a thank you to the originator and a polite note that if they ever desire to reconverge that they are very welcome.

**Comment by bartelink** [comment]
Per [the thread linked in the OP, the owner is happy for it to move outright](https://github.com/dungpa/fsharp-cheatsheet/pull/13#issuecomment-1757697357) and will thus assent to a move if it's possible to do that as part of the process ?

Definitely appreciate @dungpa's stewardship thus far and the acknowledgement note is a given - I know it helped me a lot at the right time in my journey

**Comment by dungpa** [comment]
Can anyone add me to the `fsprojects` organisation to kick off the ownership transfer?

It's nice to transfer ownership so that new maintainers can deal with pending issues and open pull requests.

**Comment by dsyme** [comment]
@dungpa I think you can add yourself but I'll add you too :)

**Comment by dungpa** [comment]
@dsyme Thanks.

I did the repo ownership transfer.

The repository is now available at https://github.com/fsprojects/fsharp-cheatsheet.

**Comment by dsyme** [comment]
Now transferred!

@dungpa you are admin. Please add someone as 2nd maintenaner? I suggest @bartelink?

**Comment by dungpa** [comment]
I added both @bartelink and @SpiralOSS as admins.
