### ISSUE TITLE
Move FSharp.Data.JsonSchema

### ISSUE THREAD

**Issue by Eliemer** [fsprojects/FsProjectsAdmin#48]
i wanna move https://github.com/panesofglass/FSharp.Data.JsonSchema into fsproject. Im reaching out to the author cuz i dont wanna see this project die out. Writing this issue a lil preemptively while i get maintainer access to the repo

**Comment by panesofglass** [comment]
I've transferred the project to fsprojects. Please make @Eliemer a maintainer!

**Comment by sergey-tihon** [comment]
Done, welcome aboard @Eliemer!
