### ISSUE TITLE
Requesting transfer of https://github.com/EverybodyKurts/Feliz.Plotly to the fsproject namespace

### ISSUE THREAD

**Issue by EverybodyKurts** [fsprojects/FsProjectsAdmin#50]
Hello all,

I forked the `shmew/Feliz.Plotly` repository and updated dependencies and Feliz api calls. I also created a pull request [here](https://github.com/Shmew/Feliz.Plotly/pull/30). This pull request was created on March 8, 2023 and updated dependencies as well as removed webpack in favor of vite.

You can view documentation here: https://everybodykurts.github.io/Feliz.Plotly

Please let me know if you need any additional information.

Kurt

**Comment by dsyme** [comment]
Please go ahead and fork the project into fsprojects based on the policies

Please make sure copyright and licence are respected, and add a note to the README.

Welcome along!

**Comment by EverybodyKurts** [comment]
Repo has been forked into `fsprojects` and can be found here: https://github.com/fsprojects/Feliz.Plotly
