### ISSUE TITLE
fsprojects NuGet account

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsProjectsAdmin#6]
Dear Maintainers,

Recently we created new NuGet account [fsprojects](https://www.nuget.org/profiles/fsprojects) that is owned by @fsprojects/owners group (that have a full control over all [fsprojects](https://github.com/fsprojects) organization)

The goals of this account are:
- be sure that we are able to restore access to packages in the case of emergency
- to have a backup account that can take over in case some important package is not maintained

This account will not be used for publishing new version of the package.

If you are agree with goals, please feel free to add [fsprojects](https://www.nuget.org/profiles/fsprojects) to owners list of your fsprojects's packages.
@theburningmonk @ovatsus @colinbull @forki @luajalla @ptrelford @nelak @lasandell @panesofglass @dmitry-a-morozov @jbtule @dsevastianov @mavnn @ReedCopsey @duckmatt
@mausch @kimsk @dmohl @dtchepak @pezipink

Current state:
- [x] Amazon.CloudWatch.Selector
- [x] Amazon.SimpleWorkflow.Extensions
- [x] ApiaryProvider
- [x] Cricket
- [x] DynamicsCRMProvider
- [x] DynamicsNAVProvider
- [x] DynamoDb.SQL
- [x] ExcelFinancialFunctions
- [x] ExcelProvider
- [x] Filbert
- [x] Foogle.Charts
- [x] FAKE.*
- [x] Foq
- [x] FsBlog
- [x] FSharp.Collections.ParallelSeq
- [x] FSharp.Compatibility
- [x] FSharp.Compiler.CodeDom
- [x] FSharp.ComProvider
- [x] FSharp.Configuration
- [x] FSharp.Control.Reactive
- [x] FSharp.Data.DbPedia
- [x] FSharp.Data.Experimental.XenomorphProvider
- [x] FSharp.Data.HiveProvider
- [x] FSharp.Data.SqlClient
- [x] FSharp.Data.Toolbox
- [x] FSharp.Desktop.UI
- [x] FSharp.Linq.ComposableQuery
- [x] FSharp.Management
- [x] FSharp.Numerics.FuzzyIntervals
- [x] FSharp.Quotations.Evaluator
- [x] FSharp.TypeProviders.StarterPack
- [x] FSharp.ViewModule
- [x] FSharpLint
- [x] FSharpx.*
- [x] FSharpx.Observable
- [x] FsLexYacc
- [x] FsReveal
- [x] FsUnit
- [x] GraphProvider
- [x] Paket
- [x] S3Provider
- [x] SQLProvider
- [x] Tamarin
- [x] FnuPlot
- [x] FsXaml
- [x] Oxen
- [x] AzureStorageTypeProvider
- [x] Chessie 
- [x] FSharpx.Extras 
- [x] FSharp.Core.Fluent
- [x] FSharp.CloudAgent
- [x] FSharp.Interop.Dynamic
- [x] FSharp.Core.Fluent
- [x] FSharp.Control.AsyncSeq
- [x] FSharp.Text.RegexProvider

**Comment by mavnn** [comment]
Added to FSharp.TypeProviders.StarterPack

**Comment by colinbull** [comment]
Added Cricket.

**Comment by sergey-tihon** [comment]
Thanks!
If you have any objections please mention them here.

**Comment by ovatsus** [comment]
Added ApiaryProvider

**Comment by dtchepak** [comment]
Added to [RegexProvider](https://www.nuget.org/packages/RegexProvider/).

**Comment by lasandell** [comment]
Added to FSharp.ComProvider.

**Comment by dmitry-a-morozov** [comment]
Added

FSharp.Data.SqlClient
FSharp.Desktop.UI
Tamarin

**Comment by ReedCopsey** [comment]
Added to FsXaml and FSharp.ViewModule

**Comment by sergey-tihon** [comment]
@ReedCopsey Sorry, but I cannot `confirm package ownership for 'FsXaml.Wpf'`. Could you please share it once again? Thank you.

**Comment by ReedCopsey** [comment]
@sergey-tihon Done.

**Comment by forki** [comment]
done

**Comment by theburningmonk** [comment]
Added to:

* DynamoDB.SQL
* S3Provider
* Filbert
* Amazon.CloudWatch.Selector
* Amazon.SimpleWorkflow.Extensions

**Comment by sergey-tihon** [comment]
Thank you everyone!!! We are almost done, only 5 projects left
@ptrelford @nelak @jbtule @dsevastianov @dmohl

**Comment by dsevastianov** [comment]
Added to FSharp.Numerics.FuzzyIntervals

**Comment by albertjan** [comment]
added to oxen

**Comment by isaacabraham** [comment]
Added FSharp.Azure.StorageTypeProvider

**Comment by jbtule** [comment]
Added FSharp.Interop.Dynamic

**Comment by sergey-tihon** [comment]
@forki @pblasucci could you please share https://www.nuget.org/packages/Chessie ?
@dtchepak could you please share https://www.nuget.org/packages/FSharp.Text.RegexProvider/ ?

**Comment by pblasucci** [comment]
I'm not sure what you mean by "share", but I'm probably happy to do it.
:-)

(Chessie has sort of stalled out at this point, anyway)

Cheers!

Paul

**Comment by pblasucci** [comment]
Seems it's already pending approval for Chessie.

**Comment by sergey-tihon** [comment]
Sorry, by `share` I mean to add [fsproject](https://www.nuget.org/profiles/fsprojects) account to the list of owners of Chessie. I do not see pending requests...

**Comment by forki** [comment]
pretty sure there is a bug in the nuget gallery. added you again:
![image](https://cloud.githubusercontent.com/assets/57396/7915795/3fdd71e8-0880-11e5-8818-5b070237507d.png)

**Comment by dtchepak** [comment]
Done! Sorry, forgot that step when i moved the project.

**Comment by sergey-tihon** [comment]
Thanks for everyone! It seems that we are done for now. :sparkles:
