### ISSUE TITLE
oxen a persistent queue based on redis

### ISSUE THREAD

**Issue by albertjan** [fsprojects/FsProjectsAdmin#7]
We've written a queue based on redis in f#, and we would like to add it to fsprojects. 

It's based on [OptimalBits/bull](https://github.com/optimalbits/bull).

The repository is here: http://github.com/curit/oxen and the docs site is here: http://curit.github.io/oxen/

**Comment by albertjan** [comment]
@fsgit I'm unable to restart the builds on travis for oxen.

**Comment by albertjan** [comment]
I guess there was something up with travis because it works again :+1: closing this issue as oxen has been transferred

**Comment by forki** [comment]
no I did the restart. Not sure what rights you need.

**Comment by albertjan** [comment]
Ah ok. Thanks. :smile: I'll look into the permissions for travis. I believe there's a possibility to give teams restart access on travis.

**Comment by forki** [comment]
small trick if you don't find it:

* git commit -a 
* git push origin myPullRequestBranch -f

;-)

**Comment by albertjan** [comment]
Oh good one :smile:.

I did find it I just had to resync travis with github. It gives me access to the repo because I'm listed as an owner.
