### ISSUE TITLE
YC.PrettyPrinter to fsprojects migration request

### ISSUE THREAD

**Issue by gsvgit** [fsprojects/FsProjectsAdmin#8]
Please, add https://github.com/YaccConstructor/YC.PrettyPrinter to fsprojects.

* CI build is configured.
* Documentation is created.
* Based on ProjectScaffold.
* [Discussion on renaming to FSharp.Text.PrinterCombinators](https://github.com/YaccConstructor/YC.PrettyPrinter/issues/16).

**Comment by fsprojectsgit** [comment]
Welcome! Please transfer the project to organization https://github.com/orgs/fsprojects-transfer/

After that we will complete the transfer to fsprojects

**Comment by gsvgit** [comment]
Done

**Comment by fsprojectsgit** [comment]
OK, migrated, you have admin access at https://github.com/fsprojects/YC.PrettyPrinter.  Happy incubating!

**Comment by gsvgit** [comment]
Thanks. I'm in YC Prettyprinters team, but there are no [repositories in it](https://github.com/orgs/fsprojects/teams). Could you add YC.PrettuPrinter repo to YC Prettyprinters team?

**Comment by fsprojectsgit** [comment]
fixed, thanks
