### ISSUE TITLE
Transferring jbfp/fsharp-dnx-templates to fsprojects

### ISSUE THREAD

**Issue by jbfp** [fsprojects/FsProjectsAdmin#9]
Hi, can I transfer https://github.com/jbfp/fsharp-dnx-templates to fsprojects? :)

**Comment by fsprojectsgit** [comment]
Great! Please accept the invitation you've just been sent and transfer the repo to https://github.com/fsprojects-transfer/

**Comment by fsprojectsgit** [comment]
We will then complete the transfer into this organization

**Comment by fsprojectsgit** [comment]
Scratch that - just transfer directly to http://github.com/fsprojects after accepting the invite to that repo.  You should now have access rights you need to do that

**Comment by jbfp** [comment]
Done! :)

**Comment by fsprojectsgit** [comment]
You now have write access too

**Comment by fsprojectsgit** [comment]
Ifpossible please add a README with a maintainers section, like this one.  https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/README.md.  Also for fsharp-dnx.

**Comment by jbfp** [comment]
I've added the section to fsharp-dnx-templates, @Alxandr is in charge of the fsharp-dnx project

**Comment by fsprojectsgit** [comment]
ok, done!
